name: fpex
version: '0.0.0'

extra-source-files:
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

default-extensions:
- DeriveGeneric
- GeneralizedNewtypeDeriving
- DerivingStrategies
- DeriveAnyClass
- NamedFieldPuns
- DataKinds
- OverloadedStrings
- ScopedTypeVariables
- RecordWildCards
- LambdaCase
- FlexibleContexts
- FlexibleInstances
- BangPatterns
- TypeOperators
- TypeFamilies
- InstanceSigs
- PatternGuards
- PolyKinds
- TupleSections
- DataKinds
- GADTs
- RankNTypes
- TypeApplications
- NumericUnderscores
- QuasiQuotes

library:
  dependencies:
  - base
  - optparse-applicative
  - extra
  - process
  - text
  - bytestring
  - directory
  - filepath
  - aeson
  - aeson-pretty
  - polysemy
  - polysemy-plugin
  - regex-tdfa
  - temporary
  source-dirs: src
  ghc-options: -O2 -flate-specialise -fspecialise-aggressively -fplugin=Polysemy.Plugin

executables:
  fpex:
    source-dirs: app
    main: Main.hs
    dependencies:
    - base
    - fpex
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  fpex-test:
    source-dirs: tests
    main: Main.hs
    dependencies:
    - base
    - fpex
    - text
    - tasty
    - tasty-hspec
    - HUnit
    - aeson
    - polysemy
    - polysemy-plugin
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -fplugin=Polysemy.Plugin
